# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pretty Programming Tips
email: semihokanp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The concept of this blog is to learn basic things which is short. I love learning small but 
  handy things about computer programming or operating system concepts. I want to share some tips
  (pretty tips) that i find out from other web sites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://semihokanpehlivan.github.io" # the base hostname & protocol for your site
twitter_username: semihokan
github_username:  semihokanpehlivan

# Build settings
markdown: kramdown
